### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by dcn0503** [juicycleff/casbin-mongodb-adapter#11]
First off, thanks to all contributors for creating and maintaining this adapter!

I am getting the `this.adapter.isFiltered` bug, using version v1.1.11, which is the most recent version on npm.  Could you update the npm package to include the recent changes to the codebase?

**Comment by hsluoyz** [comment]
@dcn0503 that issue (https://github.com/juicycleff/casbin-mongodb-adapter/issues/6) is fixed by PR: https://github.com/juicycleff/casbin-mongodb-adapter/pull/10

@juicycleff can you help make a new npmjs release?

**Comment by juicycleff** [comment]
@hsluoyz thanks for the PR. Are you reading my mind, I just pulled and want to make a release

**Comment by juicycleff** [comment]
@hsluoyz I made a release with some small improvements

**Comment by hsluoyz** [comment]
lol, that's really coincidental! 

I saw v1.2.0 is released: https://www.npmjs.com/package/casbin-mongodb-adapter/v/1.2.0

Thanks!

**Comment by dcn0503** [comment]
Convenient timing - thank you @juicycleff @hsluoyz!
