### ISSUE TITLE
Mongodb Error during removeNamedGroupingPolicies method - 

### ISSUE THREAD

**Issue by alokadhao20** [juicycleff/casbin-mongodb-adapter#14]
Hello,
I am using following version of casbin and adapter

"casbin": "5.7.1",
"casbin-mongodb-adapter": "1.2.2"

After adding batch processing in latest adapter version "1.2.2",  I am able to use **addNamedGroupingPolicies** method.
But, while trying the **removeNamedGroupingPolicies** method I am getting following error 

Reference Method - https://casbin.org/docs/en/management-api#removenamedgroupingpolicies

Example:- enforcer.removeNamedGroupingPolicies("g2", [[ "user1@xyz365.com", "Group1", "Floor1"]]);

error: MongoError: BSON field 'delete.deletes.q' is the wrong type 'array', expected type 'object'
error": {
    "ok": 0,
    "code": 14,
    "codeName": "TypeMismatch",
    "name": "MongoError"
  }

Can you please help me resolve this issue. 
Thank you.

**Comment by alokadhao20** [comment]
Also,

I have verified following methods are also not working which are in the same line. All methods to delete the policies

error: MongoError: BSON field 'delete.deletes.q' is the wrong type 'array', expected type 'object'
error": {
"ok": 0,
"code": 14,
"codeName": "TypeMismatch",
"name": "MongoError"
}

https://casbin.org/docs/en/management-api#removepolicies
https://casbin.org/docs/en/management-api#removenamedpolicies
https://casbin.org/docs/en/management-api#removegroupingpolicies
https://casbin.org/docs/en/management-api#removenamedgroupingpolicies

I believe all the methods should have common fix.

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403
