### ISSUE TITLE
Why force users to install with yarn?

### ISSUE THREAD

**Issue by fchristl** [juicycleff/casbin-mongodb-adapter#2]
I am working on a project where I'd like to use this package. However, when trying to install with npm, the (intended) error message pops up: `casbin-mongo-adapter must be installed with Yarn`. 

Is there any reason behind this rather than a a preference for Yarn? I work in an all-npm environment (including our CI servers, all other team members' development environments, ...), so changing to Yarn for just this one package is not an option.

If there is no other reason rather than a preference for Yarn, would you agree to removing the preinstall hook?

Update: I find this especially confusing as the README states to install using `npm`.

**Comment by hsluoyz** [comment]
I think we can support NPM.

**Comment by fchristl** [comment]
Here's a PR that addresses the issue plus two minor build problems: https://github.com/juicycleff/casbin-mongodb-adapter/pull/3

**Comment by fchristl** [comment]
Hi @hsluoyz , did you already have a chance to take a look at my PR? It'd be great if we could get a new version published that allows installing via NPM.

**Comment by hsluoyz** [comment]
I cannot merge it. Is the owner @juicycleff here?

**Comment by juicycleff** [comment]
@fchristl @hsluoyz  I'm making a release for this now

**Comment by juicycleff** [comment]
And sorry for the delay, I was quite busy

**Comment by juicycleff** [comment]
Just made a release now, closing this. Also included some minor adjustment to the mongo collection  and database naming

**Comment by fchristl** [comment]
Great, thank you so much
